version: '3'
services:
  app: 
    image: registry.heroku.com/denapp-1/web:latest
    volumes: 
        - ./webapp:/opt/webapp
    ports: 
        - 127.0.0.1:5000:5000
    environment: 
        - PORT=5000
    command: gunicorn --bind 0.0.0.0:5000 wsgi --reload